CREATE TABLE boulders (number INT UNIQUE NOT NULL, color VARCHAR(20) NOT NULL);
INSERT INTO boulders (number, color) VALUES
(1, 'blue'),
(2, 'bright green'),
(3, 'orange'),
(4, 'turquoise'),
(5, 'brown with green tape'),
(6, 'epoxy with red tape'),
(7, 'red'),
(8, 'yellow'),
(9, 'grey with grey tape'),
(10, 'brown with red tape'),
(11, 'blue'),
(12, 'turquoise'),
(13, 'green with green tape'),
(14, 'red with green tape'),
(15, 'green'),
(16, 'red'),
(17, 'black'),
(18, 'epoxy'),
(19, 'black and white'),
(20, 'grey'),
(21, 'yellow'),
(22, 'red'),
(23, 'roof green with grey tape'),
(24, 'roof red with grey tape'),
(25, 'roof red with green tape'),
(26, 'roof blue'),
(27, 'roof wood'),
(28, 'roof green'),
(29, 'roof red'),
(30, 'roof yellow'),
(31, 'roof green with red tape'),
(32, 'roof brown'),
(33, 'roof black'),
(34, 'roof white'),
(35, 'roof grey');